name: Add binary to release
description: Add cvc5 binary to the current release
inputs:
  binary:
    description: file name of binary
  github-token:
    description: token to upload binary
runs:
  using: composite
  steps:
    - name: Rename binaries for release
      shell: bash
      run: |
        cp ${{ inputs.binary }} cvc5-${{ runner.os }}

    - name: Add binaries to release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ inputs.github-token }}
        files: cvc5-*
