# kinds.toml
#
# For documentation on this file format, please refer to
# src/theory/builtin/kinds.toml.
#

[theory]
id                 = "THEORY_QUANTIFIERS"
base_class         = "::cvc5::internal::theory::quantifiers::TheoryQuantifiers"
base_class_header  = "theory/quantifiers/theory_quantifiers.h"
properties         = ["check", "presolve"]
typechecker_header = "theory/quantifiers/theory_quantifiers_type_rules.h"

[rewriter]
class  = "::cvc5::internal::theory::quantifiers::QuantifiersRewriter"
header = "theory/quantifiers/quantifiers_rewriter.h"

[[kinds]]
type     = "operator"
name     = "FORALL"
children = "2:3"
comment  = "universally quantified formula; first parameter is an BOUND_VAR_LIST, second is quantifier body, and an optional third parameter is an INST_PATTERN_LIST"
typerule = "::cvc5::internal::theory::quantifiers::QuantifierTypeRule"

[[kinds]]
type     = "operator"
name     = "EXISTS"
children = "2:3"
comment  = "existentially quantified formula; first parameter is an BOUND_VAR_LIST, second is quantifier body, and an optional third parameter is an INST_PATTERN_LIST"
typerule = "::cvc5::internal::theory::quantifiers::QuantifierTypeRule"

[[kinds]]
type    = "variable"
name    = "INST_CONSTANT"
comment = "instantiation constant"

[[kinds]]
type    = "variable"
name    = "ORACLE"
comment = "oracle"

[[kinds]]
type         = "sort"
name         = "BOUND_VAR_LIST_TYPE"
cardinality  = "Cardinality::INTEGERS"
well_founded = false
comment      = "the type of bound variable lists"

[[kinds]]
type     = "operator"
name     = "BOUND_VAR_LIST"
children = "1:"
comment  = "a list of bound variables (used to bind variables under a quantifier)"
typerule = "::cvc5::internal::theory::quantifiers::QuantifierBoundVarListTypeRule"

[[kinds]]
type         = "sort"
name         = "INST_PATTERN_TYPE"
cardinality  = "Cardinality::INTEGERS"
well_founded = false
comment      = "instantiation pattern type"

# Instantiation pattern, also called trigger.
# This node is used for specifying hints for quantifier instantiation.
# An instantiation pattern may have more than 1 child, in which case it specifies a multi-trigger.
[[kinds]]
type     = "operator"
name     = "INST_PATTERN"
children = "1:"
comment  = "instantiation pattern"
typerule = "::cvc5::internal::theory::quantifiers::QuantifierInstPatternTypeRule"

[[kinds]]
type     = "operator"
name     = "INST_NO_PATTERN"
children = 1
comment  = "instantiation no-pattern"
typerule = "::cvc5::internal::theory::quantifiers::QuantifierAnnotationTypeRule"

[[kinds]]
type     = "operator"
name     = "INST_ATTRIBUTE"
children = "1:"
comment  = "instantiation attribute"
typerule = "::cvc5::internal::theory::quantifiers::QuantifierAnnotationTypeRule"

[[kinds]]
type     = "operator"
name     = "INST_POOL"
children = "1:"
comment  = "instantiation pool"
typerule = "::cvc5::internal::theory::quantifiers::QuantifierAnnotationTypeRule"

[[kinds]]
type     = "operator"
name     = "INST_ADD_TO_POOL"
children = 2
comment  = "instantiation add to pool"
typerule = "::cvc5::internal::theory::quantifiers::QuantifierAnnotationTypeRule"

[[kinds]]
type     = "operator"
name     = "SKOLEM_ADD_TO_POOL"
children = 2
comment  = "skolemization add to pool"
# oracle formula generator is a pair (assumption generator, constraint generator)
typerule = "::cvc5::internal::theory::quantifiers::QuantifierAnnotationTypeRule"

[[kinds]]
type     = "operator"
name     = "ORACLE_FORMULA_GEN"
children = 2
comment  = "oracle interface"
typerule = "::cvc5::internal::theory::quantifiers::QuantifierOracleFormulaGenTypeRule"

[[kinds]]
type         = "sort"
name         = "INST_PATTERN_LIST_TYPE"
cardinality  = "Cardinality::INTEGERS"
well_founded = false
comment      = "the type of instantiation pattern lists"

# a list of instantiation patterns
[[kinds]]
type     = "operator"
name     = "INST_PATTERN_LIST"
children = "1:"
comment  = "a list of instantiation patterns"
typerule = "::cvc5::internal::theory::quantifiers::QuantifierInstPatternListTypeRule"
