#!/bin/bash -ex
#
# configure-in-place
# Morgan Deters <mdeters@cs.nyu.edu> for CVC4
# Copyright (c) 2010-2014  The CVC4 Project
#
# usage: configure-in-place [ arguments... ]
#
# This script configures CVC4 in the source directory (from where it
# should be invoked).
#

if [ -e .git ] && ! [ x"$1" = x-f ]; then
  echo
  echo "DO NOT USE THIS IN GIT WORKING DIRECTORIES!"
  echo
  echo "You might accidentally commit Makefiles in the source directories"
  echo "improperly, since they exist in the source directory for"
  echo "another purpose."
  echo
  exit 1
fi

if [ x"$1" = x-f ]; then
  shift
fi

./configure "$@"
CURRENT_BUILD="$(grep '^CURRENT_BUILD *= *' builds/current | awk 'BEGIN {FS=" *= *"} {print$2}')"
builds/$CURRENT_BUILD/config.status
