#!/bin/bash

cvc4="${CVC4_HOME}/cvc4"

# This is the set of command line arguments that is required to be strictly
# complaint with the input and output requirements of the current SMT-LIB
# standard.
"$cvc4" --lang=smt2 --output-lang=smt2 --strict-parsing --expr-depth=-1 --print-success --incremental --abstract-values $@
