#!/bin/bash
#
source "$(dirname "$0")/get-script-header.sh"

if [ -e cadical ]; then
  echo 'error: file or directory "cadical" exists; please move it out of the way.' >&2
  exit 1
fi

git clone https://github.com/arminbiere/cadical cadical

cd cadical

CXXFLAGS="-fPIC" ./configure && make -j$(nproc)

echo
echo ===================== Now configure CVC4 with =====================
echo ./configure --with-cadical
