#!/usr/bin/env bash
#
source "$(dirname "$0")/get-script-header.sh"

LFSC_DIR="$DEPS_DIR/lfsc-checker"
version="61ef1dc55d2bc909656f905699b28c99ddcfc518"

setup_dep "https://github.com/CVC4/LFSC/archive/$version.tar.gz" "$LFSC_DIR"
cd "$LFSC_DIR"

mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" ..
make install -j$(nproc)

echo
echo ===================== Now configure CVC4 with =====================
echo ./configure.sh --lfsc
