#!/bin/bash
#
source "$(dirname "$0")/get-script-header.sh"

if [ -e cryptominisat4 ]; then
  echo 'error: file or directory "cryptominisat4" exists; please move it out of the way.' >&2
  exit 1
fi

version="4.2.0"

mkdir cryptominisat4
cd cryptominisat4
CRYPTOMINISAT_PATH=`pwd`

webget https://github.com/msoos/cryptominisat/archive/$version.tar.gz cryptominisat-$version.tar.gz
gunzip -f cryptominisat-$version.tar.gz
tar xfv cryptominisat-$version.tar
cd cryptominisat-$version

patch -p0 < ../../contrib/cryptominisat-4.2.0.patch
patch -p0 < ../../contrib/cryptominisat-4.2.0.second.patch 

mkdir ../build
cd ../build

cmake -DCMAKE_INSTALL_PREFIX:PATH=$CRYPTOMINISAT_PATH/install -DSTATICCOMPILE="ON" -DNOM4RI="ON"  ../cryptominisat-$version
make install -j$(nproc)

cd ../

echo
echo ===================== Now configure CVC4 with =====================
echo ./configure --with-cryptominisat --with-cryptominisat-dir=`pwd`
