#!/usr/bin/env bash
#
CONTRIB_DIR=$(pwd)/$(dirname "$0")
source "$CONTRIB_DIR/get-script-header.sh"

SYMFPU_DIR="$DEPS_DIR/symfpu-CVC4"
commit="8fbe139bf0071cbe0758d2f6690a546c69ff0053"

check_dep_dir "$SYMFPU_DIR"
setup_dep \
  "https://github.com/martin-cs/symfpu/archive/$commit.tar.gz" "$SYMFPU_DIR"
cd "$SYMFPU_DIR"
patch -p1 < $CONTRIB_DIR/symfpu.patch
install_includes core symfpu
install_includes utils symfpu

echo
echo "Using symfpu commit $commit"
echo
echo ===================== Now configure CVC4 with =====================
echo ./configure.sh --symfpu
