#!/usr/bin/env bash
#
source "$(dirname "$0")/get-script-header.sh"

CMS_DIR="$DEPS_DIR/cryptominisat5"
version="5.8.0"

check_dep_dir "$CMS_DIR"
setup_dep \
  "https://github.com/msoos/cryptominisat/archive/$version.tar.gz" \
  "$CMS_DIR"
cd "$CMS_DIR"

mkdir build
cd build
cmake -DENABLE_PYTHON_INTERFACE=OFF \
      -DSTATICCOMPILE=ON \
      -DNOM4RI=ON \
      -DONLY_SIMPLE=ON \
      -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" \
      ..

make install -j$(nproc)

echo
echo ===================== Now configure CVC4 with =====================
echo ./configure.sh --cryptominisat
