#!/bin/bash

source "$(dirname "$0")/get-script-header.sh"

if [ -z "${BUILD_TYPE}" ]; then
  BUILD_TYPE="--disable-shared --enable-static"
fi

[ -n "$HOST" ] && HOST="--host=$HOST"
[ -z "$GMPVERSION" ] && GMPVERSION=6.1.2

echo =============================================================================
echo
echo "Setting up GMP $GMPVERSION..."
echo
( set -ex
  mkdir gmp-$GMPVERSION
  cd gmp-$GMPVERSION
  gmpprefix=`pwd` &&
  mkdir src &&
  cd src &&
  webget https://gmplib.org/download/gmp/gmp-$GMPVERSION.tar.bz2 gmp-$GMPVERSION.tar.bz2 &&
  tar xfj gmp-$GMPVERSION.tar.bz2 &&
  cd gmp-$GMPVERSION &&
  ./configure ${HOST} --prefix="$gmpprefix" --enable-cxx ${BUILD_TYPE} &&
  make CFLAGS="${MAKE_CFLAGS}" CXXFLAGS="${MAKE_CXXFLAGS}" LDFLAGS="${MAKE_LDFLAGS}" &&
  make install
) || exit 1
echo
