#!/usr/bin/env bash
#
source "$(dirname "$0")/get-script-header.sh"

CADICAL_DIR="$DEPS_DIR/cadical"
version="rel-1.2.1"

check_dep_dir "$CADICAL_DIR"
setup_dep \
  "https://github.com/arminbiere/cadical/archive/$version.tar.gz" "$CADICAL_DIR"
cd "$CADICAL_DIR"

CXXFLAGS="-fPIC" ./configure && make -j$(nproc)

install_lib build/libcadical.a
install_includes src/cadical.hpp

echo
echo "Using CaDiCaL version $version"
echo
echo ===================== Now configure CVC4 with =====================
echo ./configure.sh --cadical
