#!/bin/bash
#
set -e

version="4.2.0"

cd "$(dirname "$0")/.."

if ! [ -e src/parser/cvc/Cvc.g ]; then
  echo "$(basename $0): I expect to be in the contrib/ of a CVC4 source tree," >&2
  echo "but apparently:" >&2
  echo >&2
  echo "  $(pwd)" >&2
  echo >&2
  echo "is not a CVC4 source tree ?!" >&2
  exit 1
fi

function webget {
  if which wget &>/dev/null; then
    wget -c -O "$2" "$1"
  elif which curl &>/dev/null; then
    curl "$1" >"$2"
  else
    echo "Can't figure out how to download from web.  Please install wget or curl." >&2
    exit 1
  fi
}

if [ -e cryptominisat4 ]; then
  echo 'error: file or directory "cryptominisat4" exists; please move it out of the way.' >&2
  exit 1
fi

mkdir cryptominisat4
cd cryptominisat4
CRYPTOMINISAT_PATH=`pwd`

webget https://github.com/msoos/cryptominisat/archive/$version.tar.gz cryptominisat-$version.tar.gz
gunzip -f cryptominisat-$version.tar.gz
tar xfv cryptominisat-$version.tar
cd cryptominisat-$version

patch -p0 < ../../contrib/cryptominisat-4.2.0.patch
patch -p0 < ../../contrib/cryptominisat-4.2.0.second.patch 

mkdir ../build
cd ../build

cmake -DCMAKE_INSTALL_PREFIX:PATH=$CRYPTOMINISAT_PATH/install -DSTATICCOMPILE="ON" -DNOM4RI="ON"  ../cryptominisat-$version
make install -j2

cd ../

echo
echo ===================== Now configure CVC4 with =====================
echo ./configure --with-cryptominisat --with-cryptominisat-dir=`pwd`
