#!/usr/bin/env bash
#
source "$(dirname "$0")/get-script-header.sh"

# get the full path to the contrib dir; needs to be the full path so we can
# refer the patch from within the 'glpk-cut-log' build directory
contrib_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd -P)"

# Get the full path the patch we wish to apply
patch_file=${contrib_dir}/glpk-cut-log.patch

GLPK_DIR="$DEPS_DIR/glpk-cut-log"
version="4.52"

setup_dep \
  "https://ftp.gnu.org/gnu/glpk/glpk-${version}.tar.gz" \
  "$GLPK_DIR"
cd "$GLPK_DIR"

patch -p1 < ${patch_file}

if [[ "$OSTYPE" == "darwin"* ]]; then
    glibtoolize
else
    libtoolize
fi
aclocal
autoheader
autoconf
automake --add-missing

./configure --without-pic --prefix="$INSTALL_DIR" --disable-shared --enable-static --disable-dependency-tracking
make install -j$(nproc)
make distclean

# Find and move the static build
rename_installed_lib "libglpk.a" "libglpk-static.a"

./configure --with-pic --prefix="$INSTALL_DIR" --disable-shared --enable-static --disable-dependency-tracking
make install -j$(nproc)

echo
echo ===================== Now configure cvc5 with =====================
echo ./configure.sh --gpl --glpk
