#!/usr/bin/env bash
#
source "$(dirname "$0")/get-script-header.sh"

SYMFPU_DIR="$DEPS_DIR/symfpu-CVC4"
commit="8fbe139bf0071cbe0758d2f6690a546c69ff0053"

setup_dep \
  "https://github.com/martin-cs/symfpu/archive/$commit.tar.gz" "$SYMFPU_DIR"
cd "$SYMFPU_DIR"
install_includes core symfpu
install_includes utils symfpu

echo
echo "Using symfpu commit $commit"
echo
echo ===================== Now configure CVC4 with =====================
echo ./configure.sh --symfpu
