#!/usr/bin/env bash
#
source "$(dirname "$0")/get-script-header.sh"

GLPK_DIR="$DEPS_DIR/glpk-cut-log"
commit=b420454e732f4b3d229c552ef7cd46fec75fe65c

check_dep_dir "$GLPK_DIR"
setup_dep \
  "https://github.com/timothy-king/glpk-cut-log/archive/$commit.tar.gz" \
  "$GLPK_DIR"
cd "$GLPK_DIR"

libtoolize
aclocal
autoheader
autoconf
automake --add-missing

./configure --without-pic --prefix="$INSTALL_DIR" --disable-shared --enable-static --disable-dependency-tracking
make install -j$(nproc)
make distclean
mv "$INSTALL_LIB_DIR/libglpk.a" "$INSTALL_LIB_DIR/libglpk-static.a"

./configure --with-pic --prefix="$INSTALL_DIR" --disable-shared --enable-static --disable-dependency-tracking
make install -j$(nproc)

echo
echo ===================== Now configure CVC4 with =====================
echo ./configure.sh --gpl --glpk
