#!/bin/bash
#
source "$(dirname "$0")/get-script-header.sh"

wdir="symfpu-CVC4"

if [ -e $wdir ]; then
  echo "error: file or directory "$wdir" exists; please move it out of the way." >&2
  exit 1
fi

commit="1273dc9379b36af1461fe04aa453db82408006cf"

mkdir $wdir
cd $wdir
git clone https://github.com/martin-cs/symfpu.git symfpu
cd symfpu
git checkout $commit

echo
echo "Using symfpu commit $commit"
echo
echo ===================== Now configure CVC4 with =====================
echo ./configure --with-symfpu
