#!/usr/bin/env bash
#
# This script should only be used if your distribution does not ship with the
# GMP configuration you need. For example, for cross-compiling GMP for Windows
# or Linux ARM platforms. You can also use the script if your
# distribution does not ship with static GMP libraries (e.g., Arch Linux) and
# you want to build CVC4 statically.
# In most of the cases the GMP version installed on your system is the one you
# want and should use.
#

source "$(dirname "$0")/get-script-header.sh"

CONFIG=
while :; do
  case $1 in
    --host=?*)
      host=${1#*=}
      CONFIG="--host=$host"
      ;;
    --host=)
      echo "Error: empty --host="
      exit 1
      ;;
    *)
      break
  esac
  shift
done

[ -z "${BUILD_TYPE}" ] && BUILD_TYPE="--disable-shared --enable-static"
[ -z "$GMPVERSION" ] && GMPVERSION=6.2.1

GMP_DIR="$DEPS_DIR/gmp-$GMPVERSION"
rm -rf "$GMP_DIR"

echo =============================================================================
echo
echo "This script should only be used if your distribution does not ship with the"
echo "GMP configuration you need. For example, for cross-compiling GMP for"
echo "Windows or Linux ARM platforms. You can also use the script if your Linux"
echo "distribution does not ship with static GMP libraries (e.g., Arch Linux)"
echo "and you want to build CVC4 statically."
echo
echo "In most of the cases the GMP version installed on your system is the one you"
echo "want and should use."
echo
echo =============================================================================
echo
echo "Setting up GMP $GMPVERSION..."
echo
setup_dep "https://gmplib.org/download/gmp/gmp-$GMPVERSION.tar.bz2" "$GMP_DIR"
cd "$GMP_DIR"
./configure ${CONFIG} --prefix="$INSTALL_DIR" --enable-cxx ${BUILD_TYPE}
make \
  CFLAGS="${MAKE_CFLAGS}" \
  CXXFLAGS="${MAKE_CXXFLAGS}" \
  LDFLAGS="${MAKE_LDFLAGS}" \
  -j$(nproc)
make install
echo
