#!/bin/bash
echo "Make regress with stats..."
make regress $@ CVC4_REGRESSION_ARGS=--stats >& temp.txt
echo "Do grep for rule checks..."
cat temp.txt | grep ruleChecks > temp-rc.txt
rm temp.txt
echo "Clean..."
sed -i $'s/[^[:print:]\t]//g' temp-rc.txt
sed -i 's/\[92m+ProofCheckerStatistics::ruleChecks, "\[//g; s/)/\n/g; s/,//g; s/ (//g; s/(//g; s/]"\[0m//g; s/ : /,/g' temp-rc.txt
sed -i '/^$/d' temp-rc.txt
# echo "Aggregate..."
awk -F, '{a[$1]+=$2;}END{for(i in a)print i", "a[i];}' temp-rc.txt
rm temp-rc.txt
