#!/bin/bash

cvc4=./cvc4
bench="$1"

file=${bench##*/}
filename=${file%.*}

echo "------- cvc4-tff casc j7 : $bench at $2..."

# use: trywith [params..]
# to attempt a run.  If an SZS ontology result is printed, then
# the run script terminates immediately.  Otherwise, this
# function returns normally.
function trywith {
  limit=$1; shift;
  echo "--- Run $@ at $limit...";
  (ulimit -t "$limit";$cvc4 --lang=tptp --no-checking --no-interactive "$@" $bench) 2>/dev/null |
  (read w1 w2 w3 result w4 w5;
  case "$result" in
  Unsatisfiable) echo "$w1 $w2 $w3 $result $w4 $w5";cat;exit 0;;
  Theorem) echo "$w1 $w2 $w3 $result $w4 $w5";cat;exit 0;;
  esac; exit 1)
  if [ ${PIPESTATUS[1]} -eq 0 ]; then exit 0; fi
}
function finishwith {
  echo "--- Run $@...";
  $cvc4 --lang=tptp --no-checking --no-interactive "$@" $bench
}

trywith 15 --cbqi-recurse --full-saturate-quant
trywith 15 --decision=internal --full-saturate-quant
trywith 30 --quant-cf --qcf-tconstraint --full-saturate-quant
trywith 20 --finite-model-find
trywith 30 --fmf-bound-int
trywith 60 --quant-cf --full-saturate-quant
finishwith --cbqi-recurse --full-saturate-quant --pre-skolem-quant
# echo "% SZS status" "GaveUp for $filename"
