#!/bin/bash

dir="$(dirname "$0")"

find src \( -name '*.cpp' -o -name '*.h' \) \! -path 'src/prop/minisat/*' \! -path 'src/prop/bvminisat/*' \! -path 'src/parser/*/generated/*' |
  while read f; do
    misspelled_words=`
    $dir/extract-strings-and-comments $f |
      ispell -a -W 3 2>/dev/null |
      tail -n +2 |
        while read s; do
          case "$s" in
            \**|\+*|-*) ;;
            \&*|\#*|\?*) echo "$s" | awk '{print$2}';;
#           *) test -n "$s" && echo "UNKNOWN : $s";;
          esac
        done | sort -fu | sed 's,^,  ,'`
    if [ -n "$misspelled_words" ]; then
      echo "$f"
      echo "$misspelled_words"
    fi
  done
