#!/bin/bash

CVC4_DIR=/space/ajreynol/cvc4

echo "Update LFSC"
$CVC4_DIR/contrib/get-lfsc-checker

# HACK: update the regression script
cp $CVC4_DIR/test/regress/run_regression.py $CVC4_DIR/test/regress/temp.py
cp $CVC4_DIR/test/regress/extract_regression_calls.py $CVC4_DIR/test/regress/run_regression.py

echo "Make the LFSC regression script"
make regress | grep CALL: >& temp.txt

# HACK: revert changes to regression script
cp $CVC4_DIR/test/regress/temp.py $CVC4_DIR/test/regress/run_regression.py

sed -i 's/\CALL:/run_regression_lfsc/g' temp.txt

echo "#!/bin/bash" > run_regressions_lfsc
cat temp.txt  >> run_regressions_lfsc
chmod 755 run_regressions_lfsc
rm temp.txt

echo "Run the LFSC regression script"
./run_regressions_lfsc >& lfsc-regression-results.txt

echo "================ CVC4+LFSC results"
echo -n "SUCCESS: "
cat lfsc-regression-results.txt | grep "SUCCESS" | wc -l
echo -n "WARNING: "
cat lfsc-regression-results.txt | grep "WARNING" | wc -l
echo -n "ERROR-LFSC: "
cat lfsc-regression-results.txt | grep "ERROR-LFSC" | wc -l
echo -n "ERROR-CVC4: "
cat lfsc-regression-results.txt | grep "ERROR-CVC4" | wc -l
echo "================"
