(benchmark ext_con_004_001_1024.smt
:source { Generated by Roberto Bruttomesso }
:status unsat
:category { crafted }
:logic QF_BV
:extrafuns ((a BitVec[1024]))
:extrafuns ((dummy BitVec[256]))
:extrafuns ((v1 BitVec[1024]))
:extrafuns ((v2 BitVec[1024]))
:extrafuns ((v3 BitVec[1024]))
:extrafuns ((v4 BitVec[1024]))
:formula
(let (?shared a)
(and
(not (= (extract[767:512] v1) (extract[511:256] v1)))
(not (= (extract[767:512] v2) (extract[511:256] v2)))
(not (= (extract[767:512] v3) (extract[511:256] v3)))
(not (= (extract[767:512] v4) (extract[511:256] v4)))
(or
(and (= (extract[1023:256] ?shared) (concat (extract[1023:512] v1    ) dummy)) (= (extract[767:0] ?shared) (concat dummy (extract[511:0] v1    ))))
(and (= (extract[1023:256] ?shared) (concat (extract[1023:512] v2    ) dummy)) (= (extract[767:0] ?shared) (concat dummy (extract[511:0] v2    ))))
(and (= (extract[1023:256] ?shared) (concat (extract[1023:512] v3    ) dummy)) (= (extract[767:0] ?shared) (concat dummy (extract[511:0] v3    ))))
(and (= (extract[1023:256] ?shared) (concat (extract[1023:512] v4    ) dummy)) (= (extract[767:0] ?shared) (concat dummy (extract[511:0] v4    ))))
)
))
)
