#!/bin/bash
#
# mktagheaders
#
# The purpose of this script is to generate the *_tag.h header file from the
# *_tags file.
#
# Invocation:
#
#    mktagheaders <tag-file>
#

TAG_FILE=$1

echo 'static char const* const '$TAG_FILE'[] = {';
for tag in `cat $TAG_FILE`; do
  echo "\"$$tag\",";
done;
echo 'NULL';
echo '};'
