id     = "PRINTER"
name   = "Printing"

[[option]]
  name       = "flattenHOChains"
  category   = "regular"
  long       = "flatten-ho-chains"
  type       = "bool"
  default    = "false"
  help       = "print (binary) application chains in a flattened way, e.g. (a b c) rather than ((a b) c)"

[[option]]
  name       = "printInstMode"
  category   = "regular"
  long       = "print-inst=MODE"
  type       = "PrintInstMode"
  default    = "LIST"
  help       = "print format for printing instantiations"
  help_mode  = "Print format for printing instantiations."
[[option.mode.LIST]]
  name = "list"
  help = "Print the list of instantiations per quantified formula, when non-empty."
[[option.mode.NUM]]
  name = "num"
  help = "Print the total number of instantiations per quantified formula, when non-zero."

[[option]]
  name       = "printInstFull"
  category   = "regular"
  long       = "print-inst-full"
  type       = "bool"
  default    = "true"
  help       = "print instantiations for formulas that do not have given identifiers"
