id     = "PRINTER"
name   = "Printing"

[[option]]
  name       = "printInstMode"
  category   = "common"
  long       = "print-inst=MODE"
  type       = "PrintInstMode"
  default    = "LIST"
  help       = "print format for printing instantiations"
  help_mode  = "Print format for printing instantiations."
[[option.mode.LIST]]
  name = "list"
  help = "Print the list of instantiations per quantified formula, when non-empty."
[[option.mode.NUM]]
  name = "num"
  help = "Print the total number of instantiations per quantified formula, when non-zero."

[[option]]
  name       = "printInstFull"
  category   = "regular"
  long       = "print-inst-full"
  type       = "bool"
  default    = "true"
  help       = "print instantiations for formulas that do not have given identifiers"

[[option]]
  name       = "printUnsatCoresFull"
  category   = "regular"
  long       = "print-unsat-cores-full"
  type       = "bool"
  default    = "false"
  help       = "when printing unsat cores, include unlabeled assertions"

[[option]]
  name       = "flattenHOChains"
  category   = "expert"
  long       = "flatten-ho-chains"
  type       = "bool"
  default    = "false"
  help       = "print (binary) application chains in a flattened way, e.g. (a b c) rather than ((a b) c)"

[[option]]
  name       = "modelUninterpPrint"
  category   = "regular"
  long       = "model-u-print=MODE"
  type       = "ModelUninterpPrintMode"
  default    = "None"
  help       = "determines how to print uninterpreted elements in models"
  help_mode  = "uninterpreted elements in models printing modes."
[[option.mode.DeclSortAndFun]]
  name = "decl-sort-and-fun"
  help = "print uninterpreted elements declare-fun, and also include a declare-sort for the sort"
[[option.mode.DeclFun]]
  name = "decl-fun"
  help = "print uninterpreted elements declare-fun, but don't include a declare-sort for the sort"
[[option.mode.None]]
  name = "none"
  help = "(default) do not print declarations of uninterpreted elements in models."
