name: Configure and build
description: Run configure script and build
inputs:
  configure-env:
    default: ""
  configure-config:
    default: ""
  build-shared:
    default: true
  build-static:
    default: true
runs:
  using: composite
  steps:
    - name: Shared build
      shell: bash
      run: |
        if [[ $RUNNER_OS = "Linux" ]]; then
          sudo apt-get install -y gdb
        fi
        if [[ "${{ inputs.build-shared }}" != "true" ]]; then exit 0; fi
        ${{ inputs.configure-env }} ./configure.sh ${{ inputs.configure-config }} \
          --prefix=$(pwd)/build_shared/install \
          --werror --name=build_shared
        
        cd build_shared/
        ccache -p
        # can not use `ccache --set-config=base_dir=` due to ccache bug, fixed with 3.7.10
        touch ~/.ccache/ccache.conf
        pwd=$(pwd)
        $SED -i.orig -n -e '/^base_dir = /!p' -e "\$abase_dir = $pwd" ~/.ccache/ccache.conf
        cat ~/.ccache/ccache.conf
        ccache -p
        make -j${{ env.num_proc }}

    - name: Static build
      shell: bash
      run: |
        if [[ "${{ inputs.build-static }}" != "true" ]]; then exit 0; fi
        ${{ inputs.configure-env }} ./configure.sh ${{ inputs.configure-config }} \
          --prefix=$(pwd)/build_static/install \
          --werror --static --name=build_static

        cd build_static/
        echo $(pwd)
        pwd=$(pwd)
        $SED -i.orig -n -e '/^base_dir = /!p' -e "\$abase_dir = $pwd" ~/.ccache/ccache.conf
        ccache -p
        make -j${{ env.num_proc }}
        
    - name: Reset ccache base_dir
      shell: bash
      run: |
        $SED -i.orig -n -e '/^base_dir = /!p' -e "\$abase_dir =" ~/.ccache/ccache.conf