name: Configure and build
description: Run configure script and build
inputs:
  configure-env:
    default: ""
  configure-config:
    default: ""
  build-shared:
    default: true
  build-static:
    default: true
outputs:
  shared-build-folder:
    description: build folder of the shared build
    value: ${{ steps.shared-build.outputs.build-dir }}
  static-build-folder:
    description: build folder of the static build
    value: ${{ steps.static-build.outputs.build-dir }}
runs:
  using: composite
  steps:
    - name: Shared build
      id: shared-build
      shell: bash
      run: |
        echo "::group::Shared build"
        if [[ "${{ inputs.build-shared }}" != "true" ]]; then exit 0; fi
        ${{ inputs.configure-env }} ./configure.sh ${{ inputs.configure-config }} \
          --prefix=$(pwd)/build_shared/install \
          --werror --name=build_shared
        
        # can not use `ccache --set-config=base_dir=` due to ccache bug, fixed with 3.7.10
        cd build_shared/
        pwd=$(pwd)
        $SED -i.orig -n -e '/^base_dir = /!p' -e "\$abase_dir = $pwd" $CCACHE_CONFIGPATH
        
        time make -j${{ env.num_proc }}

        echo "::set-output name=build-dir::$pwd"
        echo "::endgroup::"

    - name: Static build
      id: static-build
      shell: bash
      run: |
        echo "::group::Static build"
        if [[ "${{ inputs.build-static }}" != "true" ]]; then exit 0; fi
        ${{ inputs.configure-env }} ./configure.sh ${{ inputs.configure-config }} \
          --prefix=$(pwd)/build_static/install \
          --werror --static --name=build_static

        cd build_static/
        pwd=$(pwd)
        $SED -i.orig -n -e '/^base_dir = /!p' -e "\$abase_dir = $pwd" $CCACHE_CONFIGPATH

        time make -j${{ env.num_proc }}

        echo "::set-output name=build-dir::$pwd"
        echo "::endgroup::"
        
    - name: Reset ccache base_dir
      shell: bash
      run: |
        echo "::group::Reset ccache base_dir"
        $SED -i.orig -n -e '/^base_dir = /!p' -e "\$abase_dir =" $CCACHE_CONFIGPATH
        echo "::endgroup::"
