name: Configure and build
description: Run configure script and build
inputs:
  configure-env:
    default: ""
  configure-config:
    default: ""
  build-shared:
    default: true
  build-static:
    default: true
runs:
  using: composite
  steps:
    - name: Shared build
      shell: bash
      run: |
        sudo apt-get install -y gdb
        if [[ "${{ inputs.build-shared }}" != "true" ]]; then exit 0; fi
        ${{ inputs.configure-env }} ./configure.sh ${{ inputs.configure-config }} \
          --prefix=$(pwd)/build_shared/install \
          --werror --name=build_shared
        
        cd build_shared/
        echo $(pwd)
        ccache -p
        gdb -ex r -ex bt --args ccache --set-config=base_dir="$(pwd)"
        make -j${{ env.num_proc }}

    - name: Static build
      shell: bash
      run: |
        if [[ "${{ inputs.build-static }}" != "true" ]]; then exit 0; fi
        ${{ inputs.configure-env }} ./configure.sh ${{ inputs.configure-config }} \
          --prefix=$(pwd)/build_static/install \
          --werror --static --name=build_static

        cd build_static/
        echo $(pwd)
        ccache -p
        gdb -ex r -ex bt --args ccache --set-config=base_dir="$(pwd)"
        make -j${{ env.num_proc }}
        
    - name: Reset ccache base_dir
      shell: bash
      run: |
        ccache --set-config=base_dir=