#!/bin/bash

cvc5=$(dirname "$(readlink -f "$0")")/cvc5
bench="$1"

logic=$(expr "$(grep -m1 '^[^;]*set-logic' "$bench")" : ' *(set-logic  *\([A-Z_]*\) *) *$')

# use: finishwith [params..]
# to run cvc5 and let it output whatever it will to stdout.
function finishwith {
  $cvc5 -L smt2.6 --no-incremental --no-type-checking --no-interactive "$@" $bench
}

case "$logic" in

QF_LRA)
  finishwith --no-restrict-pivots --use-soi --new-prop
  ;;
QF_LIA)
  finishwith --miplib-trick --miplib-trick-subs=4 --use-approx --lemmas-on-replay-failure --replay-early-close-depth=4 --replay-lemma-reject-cut=128 --replay-reject-cut=512 --use-soi
  ;;
QF_NIA)
  finishwith --nl-ext-tplanes
  ;;
# all logics with UF + quantifiers should either fall under this or special cases below
ALIA|AUFLIA|AUFLIRA|AUFNIRA|UF|UFIDL|UFLIA|UFLRA|UFNIA|UFDT|UFDTLIA|AUFDTLIA|AUFBVDTLIA|AUFNIA|ABVFP|BVFP|FP)
  finishwith --full-saturate-quant --fp-exp
  ;;
UFBV)
  finishwith --finite-model-find
  ;;
BV)
  finishwith --full-saturate-quant --decision=internal
  ;;
LIA|LRA)
  finishwith --full-saturate-quant --cegqi-nested-qe --decision=internal
  ;;
NIA|NRA)
  finishwith --full-saturate-quant --cegqi-nested-qe --decision=internal
  ;;
QF_AUFBV)
  finishwith --decision=justification-stoponly
  ;;
QF_ABV)
  finishwith --arrays-weak-equiv
  ;;
QF_UFBV)
  finishwith
  ;;
QF_BV)
  finishwith
  ;;
QF_AUFLIA)
  finishwith --no-arrays-eager-index --arrays-eager-lemmas --decision=justification
  ;;
QF_AX)
  finishwith --no-arrays-eager-index --arrays-eager-lemmas --decision=internal
  ;;
QF_AUFNIA)
  finishwith --decision=justification --no-arrays-eager-index --arrays-eager-lemmas
  ;;
QF_ALIA)
  finishwith --decision=justification-stoponly --no-arrays-eager-index --arrays-eager-lemmas
  ;;
QF_S|QF_SLIA)
  finishwith --strings-exp
  ;;
QF_ABVFP|QF_ABVFPLRA)
  finishwith --fp-exp
  ;;
QF_BVFP|QF_BVFPLRA)
  finishwith --fp-exp
  ;;
QF_FP|QF_FPLRA)
  finishwith --fp-exp
  ;;
*)
  # just run the default
  finishwith
  ;;

esac

