#!/bin/bash

cvc4=./cvc4-application

read line
if [ "$line" != '(set-option :print-success true)' ]; then
  echo 'ERROR: first line supposed to be set-option :print-success, but got: "'"$line"'"' >&2
  exit 1
fi
echo success
read line
logic=$(expr "$line" : ' *(set-logic  *\([A-Z_]*\) *) *$')
if [ -z "$logic" ]; then
  echo 'ERROR: second line supposed to be set-logic, but got: "'"$line"'"' >&2
  exit 1
fi
echo success

function runcvc4 {
  # we run in this way for line-buffered input, otherwise memory's a
  # concern (plus it mimics what we'll end up getting from an
  # application-track trace runner?)
  $cvc4 --force-logic="$logic" -L smt2 --print-success --no-checking --no-interactive "$@" <&0-
}

case "$logic" in

QF_LRA)
  runcvc4 --tear-down-incremental --unconstrained-simp
  ;;
QF_LIA)
  # same as QF_LRA but add --pb-rewrites
  runcvc4 --tear-down-incremental --unconstrained-simp
  ;;
ALIA|AUFLIA|AUFLIRA|AUFNIRA|BV|UF|UFBV|UFIDL|UFLIA|UFLRA|UFNIA)
  runcvc4  --tear-down-incremental
  ;;
LIA|LRA|NIA|NRA)
  runcvc4 --tear-down-incremental --cbqi --no-cbqi-sat
  ;;
QF_BV)
  runcvc4 --tear-down-incremental --unconstrained-simp --bv-eq-slicer=auto --bv-div-zero-const --bv-intro-pow2
  ;;
QF_AUFLIA|QF_AX)
  runcvc4 --tear-down-incremental --no-arrays-eager-index --arrays-eager-lemmas
  ;;
*)
  # just run the default
  runcvc4 --tear-down-incremental
  ;;

esac
