#!/bin/bash

cvc5=$(dirname "$(readlink -f "$0")")/cvc5

# we run in this way for line-buffered input, otherwise memory's a
# concern (plus it mimics what we'll end up getting from an
# application-track trace runner?)
$cvc5 --incremental --use-portfolio -L smt2.6 --print-success --no-type-checking --no-interactive --fp-exp <&0-
