#!/bin/bash

cvc5=./cvc5

line=""
while [[ -z "$line" ]]; do
  read line
done
if [ "$line" != '(set-option :print-success true)' ]; then
  echo 'ERROR: first line supposed to be set-option :print-success, but got: "'"$line"'"' >&2
  exit 1
fi
echo success
line=""
while [[ -z "$line" ]]; do
  read line
done
logic=$(expr "$line" : ' *(set-logic  *\([A-Z_]*\) *) *$')
if [ -z "$logic" ]; then
  echo 'ERROR: second line supposed to be set-logic, but got: "'"$line"'"' >&2
  exit 1
fi
echo success

function runcvc5 {
  # we run in this way for line-buffered input, otherwise memory's a
  # concern (plus it mimics what we'll end up getting from an
  # application-track trace runner?)
  $cvc5 --force-logic="$logic" -L smt2.6 --print-success --no-type-checking --no-interactive "$@" <&0-
}

case "$logic" in

ALIA|ANIA|AUFNIRA|LIA|LRA|QF_ALIA|QF_ANIA|QF_AUFBVLIA|QF_AUFBVNIA|QF_LIA|QF_LRA|QF_NIA|QF_UFBVLIA|QF_UFLIA|QF_UFLRA|QF_UFNIA|UFLRA)
  runcvc5 --tear-down-incremental=1
  ;;
QF_AUFLIA)
  runcvc5 --tear-down-incremental=1 --no-arrays-eager-index --arrays-eager-lemmas
  ;;
QF_BV)
  runcvc5 --incremental --bitblast=eager --bv-sat-solver=cadical
  ;;
QF_UFBV)
  runcvc5 --incremental
  ;;
QF_UF)
  runcvc5 --incremental
  ;;
QF_AUFBV)
  runcvc5 --incremental
  ;;
QF_ABV)
  runcvc5 --incremental
  ;;
ABVFP)
  runcvc5 --incremental
  ;;
BVFP)
  runcvc5 --incremental
  ;;
QF_ABVFP)
  runcvc5 --incremental
  ;;
QF_BVFP)
  runcvc5 --incremental
  ;;
QF_FP)
  runcvc5 --incremental
  ;;
*)
  # just run the default
  runcvc5 --incremental
  ;;

esac
