#!/bin/bash

cvc4=./cvc4
bench="$1"

logic=$(expr "$(grep -m1 '^[^;]*set-logic' "$bench")" : ' *(set-logic  *\([A-Z_]*\) *) *$')

# use: trywith [params..]
# to attempt a run.  Only thing printed on stdout is "sat" or "unsat", in
# which case this run script terminates immediately.  Otherwise, this
# function returns normally.
function trywith {
  limit=$1; shift;
  result="$(ulimit -S -t "$limit";$cvc4 -L smt2 --no-incremental --no-checking --no-interactive "$@" $bench)"
  case "$result" in
    sat|unsat) echo "$result"; exit 0;;
  esac
}

# use: finishwith [params..]
# to run cvc4 and let it output whatever it will to stdout.
function finishwith {
  $cvc4 -L smt2 --no-incremental --no-checking --no-interactive "$@" $bench
}

case "$logic" in

QF_LRA)
  trywith 200 --enable-miplib-trick --miplib-trick-subs=4 --use-approx --lemmas-on-replay-failure --replay-early-close-depth=4 --replay-lemma-reject-cut=128 --replay-reject-cut=512 --unconstrained-simp --use-soi
  finishwith --no-restrict-pivots --use-soi --new-prop --unconstrained-simp
  ;;
QF_LIA)
  # same as QF_LRA but add --pb-rewrites
  finishwith --enable-miplib-trick --miplib-trick-subs=4 --use-approx --lemmas-on-replay-failure --replay-early-close-depth=4 --replay-lemma-reject-cut=128 --replay-reject-cut=512 --unconstrained-simp --use-soi --pb-rewrites
  ;;
ALIA|AUFLIA|AUFLIRA|AUFNIRA|BV|UF|UFBV|UFIDL|UFLIA|UFLRA|UFNIA)
  # the following is designed for a run time of 1500s.
  # initial runs
  trywith 20 --simplification=none --decision=internal --full-saturate-quant
  trywith 20 --quant-cf --pre-skolem-quant --full-saturate-quant
  trywith 20 --finite-model-find --mbqi=none
  # more runs...
  trywith 30 --relevant-triggers --full-saturate-quant
  trywith 30 --quant-cf --qcf-tconstraint --inst-when=last-call --full-saturate-quant
  trywith 30 --finite-model-find --mbqi=gen-ev --uf-ss-totality
  trywith 30 --disable-prenex-quant --full-saturate-quant
  trywith 20 --simplification=none --decision=internal --pre-skolem-quant --full-saturate-quant
  trywith 20 --quant-cf --quant-cf-mode=conflict --full-saturate-quant
  trywith 20 --fmf-bound-int --macros-quant
  # medium runs (2 min per)
  trywith 120 --decision=justification-stoponly --full-saturate-quant
  trywith 120 --quant-cf --qcf-tconstraint --full-saturate-quant
  trywith 120 --finite-model-find --fmf-inst-engine --sort-inference --uf-ss-fair --mbqi=gen-ev
  # last call runs (5 min per)
  trywith 300 --full-saturate-quant
  trywith 300 --finite-model-find --sort-inference --uf-ss-fair 
  finishwith --quant-cf --full-saturate-quant
  ;;
LIA|LRA|NIA|NRA)
  trywith 20 --enable-cbqi --full-saturate-quant
  trywith 20 --full-saturate-quant
  trywith 20 --cbqi-recurse --full-saturate-quant
  trywith 30 --quant-cf --full-saturate-quant
  trywith 60 --quant-cf --qcf-tconstraint --full-saturate-quant
  trywith 120 --cbqi-recurse --disable-prenex-quant --full-saturate-quant
  finishwith --cbqi-recurse --pre-skolem-quant --full-saturate-quant
  ;;
QF_AUFBV)
  trywith 600
  finishwith --decision=justification-stoponly
  ;;
QF_ABV)
  finishwith --ite-simp --simp-with-care --repeat-simp
  ;;
QF_BV)
  exec ./pcvc4 -L smt2 --no-incremental --no-checking --no-interactive \
         --threads 2 \
         --thread0 '--unconstrained-simp --bv-div-zero-const --bv-intro-pow2 --bitblast=eager --no-bv-abstraction' \
         --thread1 '--unconstrained-simp --bv-div-zero-const --bv-intro-pow2 --bv-eq-slicer=auto ' \
         --no-wait-to-join \
         "$bench"
  #trywith 10 --bv-eq-slicer=auto --decision=justification
  #trywith 60 --decision=justification
  #trywith 600 --decision=internal --bitblast-eager
  #finishwith --decision=justification --decision-use-weight --decision-weight-internal=usr1
  ;;
QF_AUFLIA|QF_AX)
  finishwith --no-arrays-eager-index --arrays-eager-lemmas
  ;;
*)
  # just run the default
  finishwith
  ;;

esac

