# -*-makefile-*-
#
# This makefile is included from parser directories in order to
# do antlr tracing.  THIS IS VERY MUCH A HACK, and is only enabled
# if CVC4_TRACE_ANTLR is defined (and not 0).  In ANTLR 3.2, we
# have to #define "println" and "System," etc., because the
# generator erroneously puts Java in C output!
#

ifeq ($(CVC4_TRACE_ANTLR),)
else

ifeq ($(CVC4_TRACE_ANTLR),0)
else

AM_CPPFLAGS += -DCVC4_TRACE_ANTLR
ANTLR_OPTS += -trace

endif

endif

