/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cvc_DatatypeDecl */

#ifndef _Included_cvc_DatatypeDecl
#define _Included_cvc_DatatypeDecl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cvc_DatatypeDecl
 * Method:    deletePointer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cvc_DatatypeDecl_deletePointer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     cvc_DatatypeDecl
 * Method:    toString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cvc_DatatypeDecl_toString
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cvc_DatatypeDecl
 * Method:    addConstructor
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_cvc_DatatypeDecl_addConstructor
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
