/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cvc_DatatypeConstructorDecl */

#ifndef _Included_cvc_DatatypeConstructorDecl
#define _Included_cvc_DatatypeConstructorDecl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cvc_DatatypeConstructorDecl
 * Method:    deletePointer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cvc_DatatypeConstructorDecl_deletePointer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     cvc_DatatypeConstructorDecl
 * Method:    toString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cvc_DatatypeConstructorDecl_toString
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cvc_DatatypeConstructorDecl
 * Method:    addSelector
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_cvc_DatatypeConstructorDecl_addSelector
  (JNIEnv *, jobject, jlong, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
