# This Makefile fragment allows one to use "make check" but also specify
# a regression level.

# Regression level 1 is the default
TESTS = $(REG0_TESTS) $(REG1_TESTS)

ifeq ($(REGRESSION_LEVEL),0)
TESTS = $(REG0_TESTS)
endif
ifeq ($(REGRESSION_LEVEL),2)
TESTS = $(REG0_TESTS) $(REG1_TESTS) $(REG2_TESTS)
endif
ifeq ($(REGRESSION_LEVEL),3)
TESTS = $(REG0_TESTS) $(REG1_TESTS) $(REG2_TESTS) $(REG3_TESTS)
endif
ifeq ($(REGRESSION_LEVEL),4)
TESTS = $(REG0_TESTS) $(REG1_TESTS) $(REG2_TESTS) $(REG3_TESTS) $(REG4_TESTS)
endif
