# This Makefile fragment allows one to use "make check" but also specify
# a regression level.
ifeq ($(REGRESSION_LEVEL),1)
SUBDIRS += regress1
endif
ifeq ($(REGRESSION_LEVEL),2)
SUBDIRS += regress1 regress2
endif
ifeq ($(REGRESSION_LEVEL),3)
SUBDIRS += regress1 regress2 regress3
endif
ifeq ($(REGRESSION_LEVEL),4)
SUBDIRS += regress1 regress2 regress3 regress4
endif
