name: Add self-contained JAR with the cvc5 Java bindings
description: |
  Creates a JAR that includes the cvc5 Java bindings
  along with the necessary native libraries.
inputs:
  build-dir:
    description: path to the build directory
  jar-name:
    description: target name of the JAR
  shell:
    default: bash
runs:
  using: composite
  steps:
    - name: Create JAR
      shell: ${{ inputs.shell }}
      run: |
        echo "::group::Create JAR"
        unzip ${{ inputs.build-dir }}/src/api/java/cvc5.jar
        jar cf ${{ inputs.jar-name }}.jar AUTHORS COPYING licenses io \
            -C ${{ inputs.build-dir }}/src/api/java/ cvc5-libs
        echo "::endgroup::"

    - name: Test JAR
      shell: ${{ inputs.shell }}
      run: |
        javac -cp "${{ inputs.jar-name }}.jar" ./examples/api/java/QuickStart.java -d .
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          java -cp "${{ inputs.jar-name }}.jar;." QuickStart
        else
          java -cp "${{ inputs.jar-name }}.jar:." QuickStart
        fi
        rm QuickStart.class

    - name: Store to latest
      if: github.ref == 'refs/heads/main'
      uses: ./.github/actions/store-to-latest
      with:
        asset-filename: ${{ inputs.jar-name }}.jar
        shell: ${{ inputs.shell }}

    - name: Store to release
      if: startsWith(github.ref, 'refs/tags/')
      shell: ${{ inputs.shell }}
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release upload $GITHUB_REF_NAME \
          ${{ inputs.jar-name }}.jar \
          --repo $GITHUB_REPOSITORY

