#!/bin/bash

cvc4=./cvc4
bench="$1"

file=${bench##*/}
filename=${file%.*}

echo "------- cvc4-fof casc 25 : $bench at $2..."

# use: trywith [params..]
# to attempt a run.  If an SZS ontology result is printed, then
# the run script terminates immediately.  Otherwise, this
# function returns normally.
function trywith {
  limit=$1; shift;
  echo "--- Run $@ at $limit...";
  (ulimit -S -t "$limit";$cvc4 --lang=tptp --no-checking --no-interactive --dump-instantiations --inst-format=szs --force-no-limit-cpu-while-dump "$@" $bench) 2>/dev/null |
  (read w1 w2 w3 result w4 w5;
  case "$result" in
  Unsatisfiable) echo "$w1 $w2 $w3 $result $w4 $w5";cat;exit 0;;
  Theorem) echo "$w1 $w2 $w3 $result $w4 $w5";cat;exit 0;;
  esac; exit 1)
  if [ ${PIPESTATUS[1]} -eq 0 ]; then exit 0; fi
}
function finishwith {
  echo "--- Run $@...";
  $cvc4 --lang=tptp --no-checking --no-interactive --dump-instantiations --inst-format=szs --force-no-limit-cpu-while-dump "$@" $bench
}

# designed for 300 seconds
trywith 15 --relevant-triggers --clause-split --full-saturate-quant 
trywith 15 --clause-split --no-e-matching --full-saturate-quant 
trywith 15 --finite-model-find --quant-cf --qcf-all-conflict --sort-inference --uf-ss-fair
trywith 5 --trigger-sel=max --full-saturate-quant
trywith 5 --relevant-triggers --clause-split --multi-trigger-when-single --full-saturate-quant 
trywith 5 --multi-trigger-when-single --multi-trigger-priority --full-saturate-quant 
trywith 5 --pre-skolem-quant --no-pre-skolem-quant-nested --full-saturate-quant
trywith 15 --relevant-triggers --decision=internal --full-saturate-quant
trywith 15 --clause-split --no-quant-cf --full-saturate-quant
trywith 15 --clause-split --trigger-sel=min --full-saturate-quant
trywith 30 --prenex-quant=none --full-saturate-quant
trywith 30 --decision=internal --simplification=none --no-inst-no-entail --no-quant-cf --full-saturate-quant
trywith 30 --finite-model-find --fmf-inst-engine --sort-inference --uf-ss-fair --mbqi=gen-ev
finishwith --term-db-mode=relevant --full-saturate-quant
# echo "% SZS status" "GaveUp for $filename"
