name: Package python wheel
description: Package cvc5 into a python wheel for a given python version
runs:
  using: composite
  steps:
    - name: Build wheels
      shell: bash
      run: |
        res=$(docker image inspect pycvc5-manylinux2014 ; echo $? ; exit 0)
        if [[ "$res" != 0 ]]; then
          echo "Need to build docker image"
          docker build -t pycvc5-manylinux2014 contrib/packaging_python/manylinux2014
        fi

        docker run --rm \
          -v contrib/packaging_python/shared:/home/pycvc5-manylinux2014/shared \
          -v build/:/home/pycvc5-manylinux2014/build \
          pycvc5-manylinux2014 \
          ./shared/build.sh
