name: Package python wheels
description: Package cvc5 into python wheels for all supported python versions
runs:
  using: composite
  steps:
    - name: Build wheels
      shell: bash
      run: |
        res=$(docker image inspect pycvc5-manylinux2014 ; echo $? ; exit 0)
        if [[ "$res" != 0 ]]; then
          echo "Need to build docker image"
          docker build -t pycvc5-manylinux2014 contrib/packaging_python/manylinux2014
        fi

        echo "***** Running in docker now"

        OPTS="production --auto-download"
        for version in 36 37 38 39 310
        do
          echo "***** Building for $version"
          docker run --rm \
            -v `pwd`:/home/pycvc5 \
            --env VERSION_SUFFIX="$version" \
            pycvc5-manylinux2014 \
            ./contrib/packaging_python/create_wheel.sh /opt/python/cp${version}-cp${version}m/bin/python "$OPTS"
        done

        cp dist*/*.whl .
