# kinds.toml
#
# For documentation on this file format, please refer to
# src/theory/builtin/kinds.toml.
#

[theory]
id                 = "THEORY_FF"
base_class         = "::cvc5::internal::theory::ff::TheoryFiniteFields"
base_class_header  = "theory/ff/theory_ff.h"
properties         = ["parametric", "check"]
typechecker_header = "theory/ff/theory_ff_type_rules.h"

[rewriter]
class  = "::cvc5::internal::theory::ff::TheoryFiniteFieldsRewriter"
header = "theory/ff/theory_ff_rewriter.h"

[[kinds]]
type      = "constant"
# Finite Fields
name      = "FINITE_FIELD_TYPE"
class_key = "struct"
cpp_type  = "FfSize"
hasher    = "::cvc5::internal::FfSizeHashFunction"
header    = "util/finite_field_value.h"
comment   = "finite field type"
[kinds.cardinality]
computer = "::cvc5::internal::theory::ff::FiniteFieldProperties::computeCardinality(%TYPE%)"
header   = "theory/ff/theory_ff_type_rules.h"
[kinds.enumerator]
class  = "::cvc5::internal::theory::ff::FiniteFieldEnumerator"
header = "theory/ff/type_enumerator.h"
[kinds.well-founded]
wellfoundedness-computer = true
ground-term-computer     = "(*cvc5::internal::theory::TypeEnumerator(%TYPE%))"
header                   = "theory/type_enumerator.h"

[[kinds]]
type      = "constant"
name      = "CONST_FINITE_FIELD"
class_key = "class"
cpp_type  = "FiniteFieldValue"
hasher    = "::cvc5::internal::FiniteFieldValueHashFunction"
header    = "util/finite_field_value.h"
comment   = "a finite-field constant; payload is an instance of the cvc5::internal::FiniteFieldValue class"
typerule  = "::cvc5::internal::theory::ff::FiniteFieldConstantTypeRule"

## ffmetic kinds
[[kinds]]
type     = "operator"
name     = "FINITE_FIELD_MULT"
children = "2:"
comment  = "multiplication of two or more field elements"
typerule = "::cvc5::internal::theory::ff::FiniteFieldFixedFieldTypeRule"

[[kinds]]
type     = "operator"
name     = "FINITE_FIELD_NEG"
children = 1
comment  = "unary negation of a field element"
typerule = "::cvc5::internal::theory::ff::FiniteFieldFixedFieldTypeRule"

[[kinds]]
type     = "operator"
name     = "FINITE_FIELD_ADD"
children = "2:"
comment  = "addition of two or more field elements"
typerule = "::cvc5::internal::theory::ff::FiniteFieldFixedFieldTypeRule"

[[kinds]]
type     = "operator"
name     = "FINITE_FIELD_BITSUM"
children = "2:"
comment  = "bitsum of field elements"
typerule = "::cvc5::internal::theory::ff::FiniteFieldFixedFieldTypeRule"
