# kinds                                                               -*- sh -*-
#
# For documentation on this file format, please refer to
# src/theory/builtin/kinds.
#

[theory]
id                 = "THEORY_FF"
base_class         = "::cvc5::internal::theory::ff::TheoryFiniteFields"
base_class_header  = "theory/ff/theory_ff.h"
properties         = ["parametric", "check"]
typechecker_header = "theory/ff/theory_ff_type_rules.h"

[rewriter]
class  = ":cvc5::internal::theory::ff::TheoryFiniteFieldsRewriter"
header = "theory/ff/theory_ff_rewriter.h"

[[constants]]
# Finite Fields
name    = "FINITE_FIELD_TYPE"
F       = "struct"
T       = "FfSize"
hasher  = "::cvc5::internal::FfSizeHashFunction"
header  = "util/finite_field_value.h"
comment = "finite field type"

[[cardinalities]]
name     = "FINITE_FIELD_TYPE"
computer = "::cvc5::internal::theory::ff::FiniteFieldProperties::computeCardinality(%TYPE%)"
header   = "theory/ff/theory_ff_type_rules.h"

[[enumerators]]
name   = "FINITE_FIELD_TYPE"
class  = "::cvc5::internal::theory::ff::FiniteFieldEnumerator"
header = "theory/ff/type_enumerator.h"

[[well-founded]]
name                     = "FINITE_FIELD_TYPE"
wellfoundedness-computer = true
ground-term-computer     = "(*cvc5::internal::theory::TypeEnumerator(%TYPE%))"
header                   = "theory/type_enumerator.h"

[[constants]]
name    = "CONST_FINITE_FIELD"
F       = "class"
T       = "FiniteFieldValue"
hasher  = "::cvc5::internal::FiniteFieldValueHashFunction"
header  = "util/finite_field_value.h"
comment = "a finite-field constant; payload is an instance of the cvc5::internal::FiniteFieldValue class"

## ffmetic kinds
[[operators]]
name     = "FINITE_FIELD_MULT"
children = "2:"
comment  = "multiplication of two or more field elements"
[[operators]]
name     = "FINITE_FIELD_NEG"
children = 1
comment  = "unary negation of a field element"
[[operators]]
name     = "FINITE_FIELD_ADD"
children = "2:"
comment  = "addition of two or more field elements"
[[operators]]
name     = "FINITE_FIELD_BITSUM"
children = "2:"
comment  = "bitsum of field elements"

[[typerules]]
name               = "CONST_FINITE_FIELD"
type_checker_class = "::cvc5::internal::theory::ff::FiniteFieldConstantTypeRule"
[[typerules]]
name               = "FINITE_FIELD_MULT"
type_checker_class = "::cvc5::internal::theory::ff::FiniteFieldFixedFieldTypeRule"
[[typerules]]
name               = "FINITE_FIELD_NEG"
type_checker_class = "::cvc5::internal::theory::ff::FiniteFieldFixedFieldTypeRule"
[[typerules]]
name               = "FINITE_FIELD_ADD"
type_checker_class = "::cvc5::internal::theory::ff::FiniteFieldFixedFieldTypeRule"
[[typerules]]
name               = "FINITE_FIELD_BITSUM"
type_checker_class = "::cvc5::internal::theory::ff::FiniteFieldFixedFieldTypeRule"
