name: Package python wheel for macOS
description: Package cvc5 into a python wheel on macOS for one python version
inputs:
  python-version:
    default: ""
  config:
    default: ""
  platform:
    default: ""
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v4
      if: runner.os == 'macOS'
      with:
        python-version: ${{ inputs.python-version }}
    
    - name: Build wheel
      shell: bash
      if: runner.os == 'macOS'
      run: |
        echo "::group::Build macOS wheel for ${{ inputs.python-version }}"
        ./contrib/packaging_python/mk_clean_wheel.sh python "${{ inputs.config }}" ${{ inputs.platform }}

        ls *.whl
        echo "::endgroup::"
