/******************************************************************************
 * Top contributors (to current version):
 *   Andrew Reynolds
 *
 * This file is part of the cvc5 project.
 *
 * Copyright (c) 2009-2021 by the authors listed in the file AUTHORS
 * in the top-level source directory and their institutional affiliations.
 * All rights reserved.  See the file COPYING in the top-level source
 * directory for licensing information.
 * ****************************************************************************
 *
 * Rewrite database
 */

#include "cvc5_private.h"

#ifndef CVC5__REWRITER__REWRITE_DB__H
#define CVC5__REWRITER__REWRITE_DB__H

#include <map>
#include <vector>

#include "expr/nary_match_trie.h"
#include "expr/nary_term_util.h"
#include "expr/node.h"
#include "expr/term_canonize.h"
#include "rewriter/rewrite_proof_rule.h"
#include "rewriter/rewrites.h"

namespace cvc5 {
namespace rewriter {

/** Type class callback */
class IsListTypeClassCallback : public expr::TypeClassCallback
{
 public:
  uint32_t getTypeClass(TNode v) override;
};

/**
 * A database of conditional rewrite rules.
 */
class RewriteDb
{
 public:
  /**
   * Constructor. The body of this method is auto-generated by the rules
   * defined in the rewrite_rules files.
   */
  RewriteDb();
  ~RewriteDb() {}
  /** Add rule, return its identifier */
  void addRule(DslPfRule id,
               const std::vector<Node> fvs,
               Node a,
               Node b,
               Node cond,
               bool isFixedPoint,
               bool isFlatForm = false);
  /** get matches */
  void getMatches(Node eq, expr::NotifyMatch* ntm);
  /** get rule for id */
  const RewriteProofRule& getRule(DslPfRule id) const;
  /** get ids for conclusion */
  const std::vector<DslPfRule>& getRuleIdsForConclusion(Node eq) const;
  /** get ids for head */
  const std::vector<DslPfRule>& getRuleIdsForHead(Node h) const;
  /** the union of free variables in all rules */
  const std::unordered_set<Node>& getAllFreeVariables() const;

 private:
  /** common constants */
  Node d_true;
  Node d_false;
  /** Callback to distinguish list variables */
  IsListTypeClassCallback d_canonCb;
  /** the term canonization utility */
  expr::TermCanonize d_canon;
  /** The match trie */
  expr::NaryMatchTrie d_mt;
  /** map ids to rewrite db rule information */
  std::map<DslPfRule, RewriteProofRule> d_rewDbRule;
  /** map conclusions to proof ids */
  std::map<Node, std::vector<DslPfRule> > d_concToRules;
  /** map head to proof ids */
  std::map<Node, std::vector<DslPfRule> > d_headToRules;
  /** dummy empty vector */
  std::vector<DslPfRule> d_emptyVec;
  /** All free variables in all rules */
  std::unordered_set<Node> d_allFv;
};

}  // namespace rewriter
}  // namespace cvc5

#endif /* CVC4__THEORY__REWRITE_DB__H */
