name: Run tests
description: Run all available tests
inputs:
  build-dir:
    default: build/
  check-examples:
    default: true
  check-install:
    default: true
  check-python-bindings:
    default: false
  regressions-args:
    default: ""
  regressions-exclude:
    default: "3-4"
  shell:
    default: bash
runs:
  using: composite
  steps:
    - name: Run CTest
      shell: ${{ inputs.shell }}
      run: |
        cd ${{ inputs.build-dir }}
        make -j${{ env.num_proc }} build-tests
        if ! ctest -j${{ env.num_proc }} --output-on-failure -LE regress[${{ inputs.regressions-exclude }}]
        then
          ctest --output-on-failure --rerun-failed
        fi
      env:
        CVC5_REGRESSION_ARGS: --no-early-exit
        RUN_REGRESSION_ARGS: ${{ inputs.regressions-args }}

    - name: Install Check
      shell: ${{ inputs.shell }}
      run: |
        if [[ "${{ inputs.check-install }}" != "true" ]]; then exit 0; fi
        cd ${{ inputs.build-dir }}
        make -j${{ env.num_proc }} install
        echo "#include <cvc5/cvc5.h>" > /tmp/test.cpp
        echo "using namespace cvc5;" >> /tmp/test.cpp
        echo "int main() { TermManager tm; Solver s(tm); return 0; }" >> /tmp/test.cpp
        c++ -std=c++17 /tmp/test.cpp -I install/include -L install/lib -lcvc5

    - name: Python Install Check
      shell: ${{ inputs.shell }}
      run: |
        if [[ "${{ inputs.check-python-bindings }}" != "true" ]]; then exit 0; fi
        PYTHON_MODULE_PATH="$(dirname $(dirname $(find ${{ inputs.build-dir }}/install -name 'cvc5_python_base*')))"
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          export PYTHONPATH="$PYTHONPATH;$(cygpath -w $PYTHON_MODULE_PATH)"
        else
          export PYTHONPATH="$PYTHONPATH:$PYTHON_MODULE_PATH"
        fi
        python3 examples/api/python/quickstart.py

    - name: Check Examples
      shell: ${{ inputs.shell }}
      run: |
        if [[ "${{ inputs.check-examples }}" != "true" ]]; then exit 0; fi
        cd examples
        mkdir -p build && cd build
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          export PATH="${{ inputs.build-dir }}/install/bin:$PATH"
          export CMAKE_GENERATOR="MSYS Makefiles"
        fi
        export CFLAGS=-Werror
        export CXXFLAGS=-Werror
        cmake .. -DCMAKE_PREFIX_PATH=${{ inputs.build-dir }}/install/lib/cmake \
          -DPython_EXECUTABLE=$(command -v python3)
        make -j${{ env.num_proc }}
        ctest -j${{ env.num_proc }} --output-on-failure
