name: Run tests
description: Run all available tests
inputs:
  check-examples:
    default: true
  check-python-bindings:
    default: false
  check-unit-tests:
    default: true
runs:
  using: composite
  steps:
    - name: Run CTest
      shell: bash
      run: |
        make -j${{ env.num_proc }} check
      env:
        ARGS: --output-on-failure -LE regress[${{ matrix.exclude_regress }}]
        CVC5_REGRESSION_ARGS: --no-early-exit
        RUN_REGRESSION_ARGS: ${{ matrix.run_regression_args }}
      working-directory: build

    - name: Run Unit Tests
      shell: bash
      run: |
        if [[ "${{ inputs.check-unit-tests }}" != "true" ]]; then exit 0; fi
        make -j${{ env.num_proc }} apitests units
      working-directory: build

    - name: Install Check
      shell: bash
      run: |
        make -j${{ env.num_proc }} install
        echo -e "#include <cvc5/cvc5.h>\nint main() { cvc5::api::Solver s; return 0; }" > /tmp/test.cpp
        g++ -std=c++17 /tmp/test.cpp -I install/include -L install/lib -lcvc5
      working-directory: build

    - name: Python Install Check
      shell: bash
      run: |
        if [[ "${{ inputs.check-python-bindings }}" != "true" ]]; then exit 0; fi
        export PYTHONPATH="$PYTHONPATH:$(dirname $(find build/install/ -name "pycvc5" -type d))"
        python3 -c "import pycvc5"

    - name: Check Examples
      shell: bash
      run: |
        if [[ "${{ inputs.check-examples }}" != "true" ]]; then exit 0; fi
        mkdir build
        cd build
        cmake .. -DCMAKE_PREFIX_PATH=$(pwd)/../../build/install/lib/cmake
        make -j${{ env.num_proc }}
        ctest -j${{ env.num_proc }} --output-on-failure
      working-directory: examples