# This makefile is separated because it's not under automake control.
# This gets confusing, because we want:
#
#  1. to (re)build only the tests in the "filtered" set of tests
#     (those that we're going to run)
#  2. run only the tests in the "filtered" set of tests.
#
# It's a pain to make automake happy.

# Add "filtered" tests to the set of TESTS
TESTS = $(filter $(TEST_PREFIX)%,$(filter %$(TEST_SUFFIX),$(UNIT_TESTS)))

# subsets of the tests, based on name
WHITE_TESTS = $(filter %_white,$(UNIT_TESTS))
BLACK_TESTS = $(filter %_black,$(UNIT_TESTS))
PUBLIC_TESTS = $(filter %_public,$(UNIT_TESTS))

# This rule forces automake to correctly build our filtered
# set of tests
check-TESTS: $(TESTS)
