#!/bin/sh

echo
echo '***************************************************************************'
echo '*                                                                         *'
echo '*  WARNING:  CxxTest not found at configure time; unit tests cannot run.  *'
echo '*                                                                         *'
echo '***************************************************************************'
echo

# skip this test, rather than reporting an error
exit 77
