on: [workflow_dispatch]
name: cmake-version

jobs:
  build:
    continue-on-error: true
    name: ubuntu:production-dbg
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cmake_version: [
          "3.12", "3.13", "3.14", "3.15", "3.16",
          "3.17", "3.18", "3.19", "3.20", "3.21"
        ]

    steps:
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.9
      with:
        cmake-version: ${{ matrix.cmake_version }}

    - uses: actions/checkout@v2

    - name: Install dependencies
      uses: ./.github/actions/install-dependencies
      with:
        with-documentation: true
        with-python-bindings: true
  
    - name: Setup caches
      uses: ./.github/actions/setup-cache
      with:
        cache-key: cmake
  
    - name: Configure
      run: |
        ./configure.sh production --auto-download --static --python-bindings --assertions --tracing --unit-testing --editline --docs \
          --prefix=$(pwd)/build/install \
          --werror

    - name: Build
      run: make -j${{ env.num_proc }}
      working-directory: build

    - name: ccache Statistics
      run: ccache -s

    - name: Run CTest
      run: make -j${{ env.num_proc }} check
      env:
        ARGS: --output-on-failure -LE regress[3-4]
        CVC5_REGRESSION_ARGS: --no-early-exit
        RUN_REGRESSION_ARGS: --no-check-unsat-cores
      working-directory: build

    - name: Run Unit Tests
      run: make -j${{ env.num_proc }} apitests units
      working-directory: build

    - name: Install Check
      run: |
        make -j${{ env.num_proc }} install
        echo -e "#include <cvc5/cvc5.h>\nint main() { cvc5::api::Solver s; return 0; }" > /tmp/test.cpp
        g++ -std=c++17 /tmp/test.cpp -I install/include -L install/lib -lcvc5
      working-directory: build

    - name: Python Install Check
      run: |
       export PYTHONPATH="$PYTHONPATH:$(dirname $(find build/install/ -name "pycvc5" -type d))"
       python3 -c "import pycvc5"

      # Examples are built for non-symfpu builds
    - name: Check Examples
      if: matrix.check-examples && runner.os == 'Linux'
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_PREFIX_PATH=$(pwd)/../../build/install/lib/cmake
        make -j${{ env.num_proc }}
        ctest -j${{ env.num_proc }} --output-on-failure
      working-directory: examples

    - name: Build Documentation
      run: |
        make -j${{ env.num_proc }} docs-gh
        if [ "${{ github.event_name }}" == "pull_request" ] ; then
          echo "${{ github.event.number }}" > docs/sphinx-gh/prnum
        fi
      working-directory: build
    
