#!/bin/bash
#
# run_java_test
# Morgan Deters, September 2011
#
# The purpose of this script is to change an automake test command
# line into something that a JVM likes.  In particular, any dir/Foo.class
# listed on the command line is stripped of its dir/ and its .class extension.
# Works only for tests in the default package.
#
args=("$@")
args[$((${#args}))]="$(echo "${args[${#args}]}" | sed 's,\(.*/\)*\(.*\)\.class$,\2,')"
echo "${args[@]}"
exec "${args[@]}"
